[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "packages/front-end/build" 

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_FLAGS = "--version" 
  NETLIFY_USE_PNPM = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 